---
- name: checking for install in {{ hadoop_dir }}...
  become: yes
  stat:
    path: '{{ hadoop_dir }}'
  changed_when: false
  register: hadoop_binary
- when: not hadoop_binary.stat.exists
  block:
    - name: downloading {{ hadoop_url }}...
      become: yes
      become_user: root
      get_url:
        url: '{{ hadoop_url }}'
        dest: '{{ hadoop_tmp_archive }}'
        checksum: '{{ hadoop_checksum }}'
        mode: 0644
    - name: unarchiving {{ hadoop_tmp_archive }} to {{ hadoop_parent_dir }}
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: '{{ hadoop_tmp_archive }}'
        dest: '{{ hadoop_parent_dir }}'
        creates: '{{ hadoop_dir }}'
  always:
    - name: rm {{ hadoop_tmp_archive }}
      become: yes
      become_user: root
      file:
        path: '{{ hadoop_tmp_archive }}'
        state: absent
- name: linking {{ hadoop_link_dir }} to {{ hadoop_dir }}...
  become: yes
  become_user: root
  file:
    state: link
    src: '{{ hadoop_dir }}'
    dest: '{{ hadoop_link_dir }}'

- name: include hadoop in the default path...
  become: yes
  become_user: root
  with_items:
    - f: hadoop.sh
      d: /etc/profile.d
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m | default("0644") }}'
